### ISSUE TITLE
Presenting resctl-demo @ CNCF SIG-Runtime

### ISSUE THREAD

**Issue by htejun** [facebookexperimental/resctl-demo#126]

**Comment by raravena80** [comment]
Hi @htejun, checking in, any idea when you might be able to present in the SIG-Runtime meeting? Thanks.

**Comment by htejun** [comment]
Sorry, I wasn't sure what the next step was and then lost track. My schedule these days is pretty flexible until late march, so I'm likely to make any time. Any suggestions? Thank you.

**Comment by raravena80** [comment]
Hi, @htejun my suggestion is to pick a date to present in one of our meetings and add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes).  Generally, the presentations last the whole hour so in that case it would be better to pick a date that has nothing on the agenda yet.  (We meet the first and third Thursday of the month)

**Comment by htejun** [comment]
Cool, put it on Mar 18th. Thanks.

**Comment by htejun** [comment]
Sorry, I had to take it out. Baby due date got moved up and I can't reliably predict availability past mid March. Looks like we'll have to put it on ice for the time being, unfortunately.
